channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11.4
  - tqdm=4.65.0
  - pillow=10.2.0
  - pandas==2.1.1
  - matplotlib==3.8.0
  - scikit-learn==1.3.2
  - huggingface_hub
  - einops
  - safetensors
  - roma
  - gradio
  - opencv-python
  - scipy
  - trimesh
  - tensorboard
  - pyglet<2
  - pip
