#!/bin/bash
#Set job requirements
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=03:00:00

conda env create -f environment.yml
source activate computer-vision-2 || conda activate computer-vision-2
# Install the required packages
FORCE_CUDA=1 pip install torch torchaudio torchvision
# Gdown to download large files without breaking
pip install gdown